print("My name is mwangi")
print("I am 18 years old")
print("I come from Kiambu County")
print("I love reading, watching movies,playing soccer etc")
print("--------------")
print("**************")
print("##############")
